### ISSUE TITLE
fastcache在windows下安装失败

### ISSUE THREAD

**Issue by dysl357085918** [Aploium/MagicWebsiteMirror#1]
想弄个youtube镜像，然后在windows搭建，报错custom_text_rewriter_enable = True这句，显示缺少fastcache模块，请用pip3 install fastcache，这样安装的话又出现了could not find a version that satisfies the requirement fastchaache(似乎没有适合的版本？？）禁用custom_text_rewriter_enable = True这句后，可以打开网页了，但是视频无法加载

**Comment by dysl357085918** [comment]
以解决了这个模块的问题，但是不知道为什么youtube只能加载网页还是不能看视频

**Comment by Aploium** [comment]
1. fastcache并不是必须的模块, 即使没有安装, 也会自动退回到标准库中对应的实现, 不会有功能损失(顶多慢一点)
2. 我其实之前一直是在Apache的wsgi环境下运行的..wsgi运行得非常好, 那个配置文件(现在更新了, 支持网页服务器和视频服务器分离)是经受住了生产环境考验的(一天3k+ UV, 1w+PV, 180GB流量, 一台网页服务器, 7台视频服务器)...
 但是基本没在直接运行下测试过bug....(orz..因为最近一直在用它开发一个网站)。 现在已经提升了直接运行的兼容性了.  youtube已经可用(但是需要修改一下hosts, 请看新的youtube配置文件)

ps: 现在直接运行不再是 `python3 MagicWebsiteMirror.py`  而是 `python3 wsgi.py`
非常感谢反馈!

**Comment by dysl357085918** [comment]
谢谢回答，不知道为何我换成了新的版本并且修改了hosts还是无法加载视频。就像下图这样：https://shancloud.cc/1.png

**Comment by Aploium** [comment]
奇怪...呃..请在config.py最下面加两句设置:
```python
developer_dump_all_traffics = True  
verbose_level = 4
```
然后再运行一下，会把所有数据dump到程序所在的目录的traffic文件夹下, 
请把所有的dump文件, 和stdout的所有输出打包发送给我
以及能不能问一下你的QQ号?(可以邮件发送给我`i@z.codes`)
(非常抱歉无法正常运行.....因为你大概是除了我以外第一个吃螃蟹的)
以及其余的配置文件(Google, twitter, instagram) 能正常运行吗?

**Comment by Aploium** [comment]
呃....你发给我的是youtube首页的dump......首页的dump没用呀.......(好吧是我没说清楚)
请你给出视频播放页面的dump....
stdout最好的话也要的.....没有stdout很难定位bug........(可以用  >  把stdout重定向到外部txt文件里然后发给我)

**Comment by dysl357085918** [comment]
不知道为何就正常了。
