### ISSUE TITLE
为什么不使用现有的reverse proxy工具呢

### ISSUE THREAD

**Issue by gaocegege** [Aploium/MagicWebsiteMirror#2]
就随便问问

**Comment by Aploium** [comment]
呃..比如说?_?

**Comment by gaocegege** [comment]
nginx~？

**Comment by Aploium** [comment]
我试过nginx...但是太简陋了. 对静态资源域名(比如说img.gstatic.com)支持很差.
然后只支持重写未编码的url, 编码后的url
比如说 https:\/\/aaa\.com\/bbb.jpg (json)
https%3a%2f%2fwww.example.com%2ffoobar.jpg (urlencode)
甚至更加变态的 json+urlencode 或者 urlencode+json  _(:з)∠)_

呃....只要google(或者百度一下) "google镜像" , 点进去就能看到那些用nginx做的
简直惨不忍睹........

google的nginx规则有人研究，维基也有一些一些简陋的..... 
youtube twitter镜像这些...nginx表示gg  ･ω･

(如果你没看到过demo站的话可以向我要网址)

**Comment by gaocegege** [comment]
zju.tools是么
主要不是你浙的，并用不了hhhhh

**Comment by gaocegege** [comment]
呃，是zju.tools么，因为不是你浙的过不去测试hhhhh

**Comment by Aploium** [comment]
我已经把验证问题答案发到你邮箱(ce.gao@outlook.com)了呀0.0 没有收到么(欢迎测试)
